global class Calculator{
	
	// Adding comment to this class
// Adding comment to this class
	// this is my second commit to github
   Static webservice Integer add(Integer x,Integer y)
      {
           return x+y;
           
           }           

   Static webservice Integer sub(Integer x, Integer y)
      {
           return x-y;
           
           }           
       public Integer multiple(Integer x,Integer y)
      {
           return x*y;
           
           }
           
           
   }